### ISSUE TITLE
Add instructions for how to grant Federalist access to a new org

### ISSUE THREAD

**Issue by jseppi** [18F/federalist.18f.gov#128]
This came up with @konklone's recent problem while trying to add a repo from the `uspki` org.

Basic steps to make it work:

1. Owner/admin of org goes to their [Settings > Authorized OAuth Apps](https://github.com/settings/applications) and selects "Federalist (GovCloud)" from the list of apps.
1. On that page, they will see a list of apps under the "Organization access" heading. They will need to click the "Grant" button next to the org:

<img width="752" alt="screen shot 2017-09-19 at 12 04 40 pm" src="https://user-images.githubusercontent.com/697848/30605182-bf9e1eac-9d32-11e7-8d5e-b9978d772a11.png">

**Comment by eddietejeda** [comment]
@amirbey does this apply anymore?

**Comment by eddietejeda** [comment]
@amirbey  Can you add this to Federalist site?

**Comment by eddietejeda** [comment]
@295
