### ISSUE TITLE
[FR] Add a page on creating data feeds 

### ISSUE THREAD

**Issue by JJediny** [18F/federalist.18f.gov#297]
# User Story
As a federalist user, I want to know the best ways to generate a single dataset from the content of my site, for search indexing/data feeds/single downloadable archives, etc of the site's collection of individual pages/posts. I also want to know how to take an external dataset (csv/json/yaml) that is relevant to my project and use them within the context of my site for cross-referencing or simplified data entry (eg `_data` folder)

# How to
Similar to https://federalist.18f.gov/pages/using-federalist/search/

Add a page for:  `Adding data feeds` or `Using and Creating Datasets`

This page could give various examples of creating data feeds xml/csv/json, from collections of individual static page(s).

Examples to include:
* robot.txt
* RSS feed
* [Sitemap.xml](https://search.gov/blog/sitemaps.html) - for search.gov ingest
* [index.json - for lunr.js local search index](https://lunrjs.com/)
* [data.json](https://project-open-data.cio.gov/v1.1/schema/) - ex. https://github.com/GSA/citizenscience.gov/pull/205/files
* site.csv - as a csv dump of the sites posts/pages - ex. https://github.com/GSA/citizenscience.gov/pull/205/files

It may also benefit the reader to include a link to another page or a section of the page on how someone can use `_data` folder to take csv/json/yaml and use that as a datasource to cross-reference, enhance, or render site contents vs the traditional yaml+markdown files

**Comment by davemcorwin** [comment]
This isn't specific to Federalist, users are probably better served finding resources specific to their build technology.
