### ISSUE TITLE
Typo on two page overview

### ISSUE THREAD

**Issue by fulldecent** [18F/federalist.18f.gov#306]
On https://federalist.18f.gov/assets/documents/Federalist-Proposal.pdf

It is stated:

> It’s easy to archive or moves your sites on or off Federalist at any time.

Should be

> It’s easy to archive or move your sites on or off Federalist at any time.

**Comment by eddietejeda** [comment]
https://github.com/18F/federalist.18f.gov/commit/5755a0e28e02ea0a758cd58d4fa2c17d9a9f1283
