### ISSUE TITLE
Proposal to reoganize the menu system 

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist.18f.gov#311]
As a user of Federalist, I need to find information on templates and features quickly, but at the moment, it's scattered in multiple places. This proposal looks to simplify the menu system.

Tabs: 
- [ ] Remove success stories tab and replace with "Methods to building your Federalist site". 
- [ ] Ensure "Features" tab language matches with new language in pricing proposal
- [ ] Ensure "Documentation" tab language matches with new language in pricing proposal. Add "Federalist fact sheets" from home page to somewhere on this page 
- [ ] Ensure "Support" tab language matches with new language in pricing proposal

**Comment by eddietejeda** [comment]
@amirahaziz, can you develop a mockup of what this layout would look like?

**Comment by Bryanthales** [comment]
I'm reassigning this to myself. If there are any objections, speak now or forever hold your peace
