### ISSUE TITLE
Draft announcement for Netlify (and other) releases 

### ISSUE THREAD

**Issue by amirahaziz** [18F/federalist.18f.gov#321]
Things to include:

New Netlify release
Introducing Amir as new PM for Federliast
Case studies 
18F blog post (Federalist + USWDS 2.0)

**Comment by eddietejeda** [comment]
Amirah wrote this, and might be useful here:
https://docs.google.com/document/d/1Qn99YTqe6IB7S6I1aSWPXwyqWINezo3FhVZ0z2RpS7s/edit?ts=5d23a2b4
