### ISSUE TITLE
Old date on page?

### ISSUE THREAD

**Issue by wslack** [18F/federalist.18f.gov#334]
https://federalist.18f.gov/success-stories/ says: `Federalist welcomes its newest client, GSA's Office of Government Wide Policy Councils Team - February 28, 2018`

Is that right?

**Comment by eddietejeda** [comment]
Oh boy, that is old. We should not have such timely notices.

**Comment by Bryanthales** [comment]
I've updated the success stories page and sent the pull to Amir for review and approval. I removed the box entirely and changed the other text to take up the entire page. It can be previewed here: https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/bh-remove-2018-new-customer-ss/success-stories/
