### ISSUE TITLE
Logo not loading in chrome or firefox

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist.18f.gov#335]
I've tested in chrome or firefox.
 
<img width="746" alt="missing logo" src="https://user-images.githubusercontent.com/669988/62911871-e9906380-bd53-11e9-9200-10a316ca2627.png">

**Comment by amirbey** [comment]
@eddietejeda - can you provide the steps to re-create this .... we were not able to re-create this during backlog grooming

**Comment by amirbey** [comment]
@Bryanthales - i've added the image as an initial step ... can you proof/size this?
https://github.com/18F/federalist.18f.gov/tree/logo-image
