### ISSUE TITLE
Homepage header text format

### ISSUE THREAD

**Issue by Bryanthales** [18F/federalist.18f.gov#339]
The text for the "There’s no easier way to build, launch, and manage government sites." header appears to be a different text format/size. 

- [x] Identify text difference
- [x] Implement fix so that text format aligns between tabs.

**Comment by Bryanthales** [comment]
Homepage: <h1 class="federalist-heading font-large">There’s no easier way to build, launch, and manage government sites.</h1>
Other Page Headers: <h1>Trusted and scalable.</h1>
*note all the other pages have the <h1> html instead of the <h1 class="federalist-heading font-large">

**Comment by Bryanthales** [comment]
@eddietejeda @amirbey  -- low priority, but we can chat on it tomorrow during standup.

Fixed it so the font is consistent; however, the top text now stretches onto three lines. I think that the text was changed to prevent this -- the 3 lines doesn't look great. You can see the effect at [site link](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/bryant---testing/)
![image](https://user-images.githubusercontent.com/42779803/64283124-aa48d300-cf0b-11e9-8d58-b4d1d12ac008.png)

**Comment by eddietejeda** [comment]
looks great! can you move "build" to the second line?

**Comment by Bryanthales** [comment]
> looks great! can you move "build" to the second line?

[Updated Version](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/Bryanthales-testingv2/)
![image](https://user-images.githubusercontent.com/42779803/64286130-b9cb1a80-cf11-11e9-83eb-ef46dfb33feb.png)
