### ISSUE TITLE
Search input is not visible

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist.18f.gov#348]
After clicking "Search" the search input is not visible to brows users.

![Screen Shot 2019-09-13 at 12 41 30 PM](https://user-images.githubusercontent.com/6662371/64890195-e1ae3280-d623-11e9-9674-8c3de14ec333.png)

**Comment by eddietejeda** [comment]
Why/how did this functionality change?

**Comment by davemcorwin** [comment]
I have no idea. The class has been there for a while.
