### ISSUE TITLE
Fix sidenav active page style

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist.18f.gov#371]
When on a documentation page, the styles on the sidenav to not indicate the currently active page. See screenshot below.

![Screen Shot 2020-01-21 at 9.26.04 AM.png](https://images.zenhubusercontent.com/55539b1a4f7a08fbb7f2c453/05cb1a67-9252-42ae-9926-55824f11fc28)

**Comment by amirbey** [comment]
#### User Story

A documentation user should be to see in the navigation menu as to which page they're on.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] the current page's menu option is highlighted
- [ ] Change made live via federalist.18f.gov

_After evaluating, edit this part:_

#### Level of effort - <low/medium/high>

#### Implementation outline (if higher than "low" effort):

- [ ] add css changes to set the background color of the current menu option
