### ISSUE TITLE
GSA privacy threshold assessment (PTA) requirement

### ISSUE THREAD

**Issue by msouaya** [18F/federalist.18f.gov#388]
Given recent opportunities (e.g., Federal Privacy Council mtg) to learn about GSA's forms as a service project, GSA's Privacy Office requests a privacy threshold assessment (PTA) to document the project.  PTAs are required of IT systems, apps and projects at GSA.  If the word project is not exactly how you'd describe forms as a service, the overarching goal is to document that personally identifiable information (PII) is not collected by forms as a service.  Offices/programs that use the service may rely on forms that collect PII, which cannot be accessed by GSA's forms as a service.  Once the PTA at the following link is submitted, someone from GSA's Privacy Office will get in touch to review and approve.  Thank you.

https://docs.google.com/forms/d/1fYME9MzhfAYuRiONJEsf1EFS9cmg03jODFq2Y9hkEgs/viewform?edit_requested=true

**Comment by amirbey** [comment]
@msouaya - Federalist is not a forms as a service project.  Users have the ability generate their site contents as they see fit.  We are not sure this is applicable.
