### ISSUE TITLE
Update proxy URL in Custom URL docs

### ISSUE THREAD

**Issue by mchelen-gov** [18F/federalist.18f.gov#427]
Is the proxy URL `https://federalist-proxy.app.cloud.gov/` correct for https://federalist.18f.gov/documentation/custom-urls/ doc?

**Comment by davemcorwin** [comment]
Removing this page as it contains either duplicate information or implementation details not necessary for customers. and moving the troubleshooting to

**Comment by davemcorwin** [comment]
Addressed in #456 , closing.
