### ISSUE TITLE
Add TXT records to custom URL docs

### ISSUE THREAD

**Issue by mchelen-gov** [18F/federalist.18f.gov#428]
https://federalist.18f.gov/documentation/custom-urls/ should document these necessary `TXT` records:

SPF
```
v=spf1 -all
```

DMARC
```
v=DMARC1; p=reject; pct=100; fo=1; ri=86400; rua=mailto:dmarcreports@gsa.gov,mailto:reports@dmarc.cyber.dhs.gov; ruf=mailto:dmarcfailures@gsa.gov
```

note: these are required only at the apex domain level

**Comment by amirbey** [comment]
#### User Story

A user launching a site should be informed of DHS compliance rules which are available in the checklist

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] add link/reference to DHS BOD-18 compliance to launch checklist
- [ ] Change made live via federalist.18f.gov

_After evaluating, edit this part:_

#### Level of effort - Low

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by davemcorwin** [comment]
I believe this was addressed in https://github.com/18F/federalist.18f.gov/pull/455. Also, https://github.com/18F/federalist.18f.gov/pull/456 adds the requested link to BOD 18-01.
