### ISSUE TITLE
Remove PTA link on https://federalist.18f.gov/documentation/forms/

### ISSUE THREAD

**Issue by rspeidel** [18F/federalist.18f.gov#481]
Hi,
GSA's privacy office has transitioned to using the Archer system for PTAs and no longer supports the google form listed on your webpage.  Please remove the link and let me know if any questions.  Remove the link:  "GSA users should start by filling out the GSA Privacy Office intake form. [https://docs.google.com/forms/d/1fYME9MzhfAYuRiONJEsf1EFS9cmg03jODFq2Y9hkEgs/viewform?edit_requested=true] 
and replace it with:  GSA users should start by filling out the GSA Privacy Office intake form, available on Insite. 
Richard

**Comment by amirbey** [comment]
thanks for raising this @rspeidel  ... can you provide us the link to the form? thanks!

**Comment by rspeidel** [comment]
Hi Amir, please check the change request.  If the new link isn't in there,
try this (from Insite):


   - Privacy Threshold Assessment (PTA) <http://archer.gsa.gov/> -
   12/07/2020
   GSA uses one PTA form to identify PII before the development or
   acquisition of a new information system and to re-certify it annually. PTAs
   are key to determining whether a Privacy Impact Assessment (PIA) is
   required, whether a System of Records Notice (SORN) is required, and if any
   other privacy requirements apply to the information system. If the system
   does not contain PII, the system's assigned Information System Security
   Officer (ISSO) will receive an automated annual recertification reminder by
   email. Please see the Archer standard operating procedure (SOP
   <https://docs.google.com/document/d/16rDU57cg0KBtisMYtPdJc7AvxckHmjTe82PNP3OHTE4/edit>)
   for completing the PTA.



Richard Speidel, J.D., CIPP/G
Chief Privacy Officer
Enterprise Data & Privacy Management Office (IDE)
General Services Administration
richard.speidel@gsa.gov

**Comment by davemcorwin** [comment]
@rspeidel Just trying to get some clarity on this. If you like we can just replace the current text and link with ONLY the text:
>  GSA users should start by filling out the GSA Privacy Office intake form, available on Insite.

But it would be more helpful to our users to actually provide the link to the new form on Insite. I did a cursory check on Insite and was unable to track it down myself. Regarding the Google Form you included in your last comment, I don't have access to this so I'm guessing many GSA users also don't have access.

If you can provide the link to the form on Insite, I can make this change to our documentation.


Thanks!

**Comment by rspeidel** [comment]
David,

You make a great point and I inadvertently skipped over a process change in
the original request.  GSA Privacy and Security are asking system owners
(and/or former PTA submitters) to work w their ISSO and privacy analyst
when considering a new system/app or major change.  Then the ISSO will
complete the PTA within the Archer system, where it now resides, and the
Privacy analyst will review and approve.  How does this sound instead:

GSA uses one PTA form to identify PII before the development or acquisition
of a new information system and to re-certify it annually. PTAs are key to
determining whether a Privacy Impact Assessment (PIA) is required, whether
a System of Records Notice (SORN) is required, and if any other privacy
requirements apply to the information system.  If you are developing,
acquiring or significantly modifying a system or application, work with
your ISSO and privacy analyst to complete a PTA early in your process.

Richard






Richard Speidel, J.D., CIPP/G
Chief Privacy Officer
Enterprise Data & Privacy Management Office (IDE)
General Services Administration
richard.speidel@gsa.gov

**Comment by davemcorwin** [comment]
@rspeidel Please let us know if the updated content in following looks ok: https://federalist-a44a7672-afb1-473e-acb2-067f644c0967.app.cloud.gov/preview/18f/federalist.18f.gov/481-pta-link/documentation/forms/

In particular:
<img width="591" alt="Screen Shot 2021-01-06 at 2 01 19 PM" src="https://user-images.githubusercontent.com/6662371/103823860-baa11e80-5027-11eb-98c4-d711fdddbfac.png">

**Comment by rspeidel** [comment]
Looks good, thanks!
Richard Speidel, J.D., CIPP/G
Chief Privacy Officer
Enterprise Data & Privacy Management Office (IDE)
General Services Administration
richard.speidel@gsa.gov
