### ISSUE TITLE
Remove DOI and AFWERX as success stories from federalist.18f.gov as they are no longer customers. Maybe find new ones?

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist.18f.gov#538]
#### User Story

Sites that are no longer Federalist customers should not be featured in "success stories".

#### Acceptance Criteria

- [x] DOI and AFWERX sites are no longer in "success stories" or "case studies"
- [x] Change made live via deploy federalist.18f.gov.

**Comment by apburnes** [comment]
Posed the question to the business team on the process for adding new customer success stories.

**Comment by apburnes** [comment]
Closed by #539
