### ISSUE TITLE
Add example values for provided environment variables

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist.18f.gov#546]
#### User Story

As a user I want to understand what values I should expected in the platform-provided environment variables.

https://federalist.18f.gov/documentation/env-vars-on-federalist-builds/

#### Acceptance Criteria

- [x] The Default environment values table should include a third column with example values
- [x] Change made live via deploy federalist documentation.

**Comment by hursey013** [comment]
Closed with https://github.com/18F/federalist.18f.gov/pull/547
